[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "8.11.4"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"